version: "3.4"
services:
  redis:
    image: redis
  web:
    build: .
    image: registry.digitalocean.com/radical-sloth/stranger-things-lights
    environment:
        - REDIS_HOST=redis
        - SERVER_KEY=test
    depends_on:
      - "redis"
    ports:
      - "5000:5000"
