apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stranger-things
  name: web
  labels:
    app: stranger-things
    tier: flask
spec:
  selector:
    matchLabels:
      app: stranger-things
      tier: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: stranger-things
        tier: flask
    spec:
      containers:
      - name: stranger-things
        image: registry.digitalocean.com/radical-sloth/stranger-things-lights:latest
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: "redis.stranger-things.svc.cluster.local"
          - name: SERVER_KEY
            valueFrom:
              secretKeyRef:
                name: web
                key: server_key
        ports:
        - containerPort: 5000
