apiVersion: v1
kind: Service
metadata:
  namespace: stranger-things
  name: stranger-things
spec:
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: stranger-things-lights-web
