apiVersion: v1
kind: Service
metadata:
  namespace: stranger-things
  name: web
  labels:
    app: stranger-things
    tier: flask
spec:
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: stranger-things
    tier: flask
