apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stranger-things
  name: redis
  labels:
    app: stranger-things
    tier: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stranger-things
      tier: redis
  template:
    metadata:
      labels:
        app: stranger-things
        tier: redis
    spec:
      containers:
        - image: redis:6
          name: redis
          ports:
            - containerPort: 6379
              name: redis
